port: 8900
load_balancer_strategy: "round_robin"
health_check_interval_seconds: 3
servers:
- url: http://localhost:8080
  health_url: http://localhost:8080/health
- url: http://localhost:8081
  health_url: http://localhost:8081/health