port: 8900
load_balancer_strategy: "round_robin"
health_check_interval_seconds: 3
rate_limiter_enabled: True
rate_limit_tokens: 10
rate_limit_interval_seconds: 10
servers:
- name: server1
  url: http://localhost:8080
  health_url: http://localhost:8080/health
- name: server2
  url: http://localhost:8081
  health_url: http://localhost:8081/health
routing:
  rules:
    - conditions:
        - path_prefix: "/api/v1"
          method: "GET"
          headers:
            useragent: "Mobile"
      action:
        route_to: server1
  default_server: server2